branch-defaults:
  master:
    environment: django-env
global:
  application_name: img-2-caption
  branch: null
  default_ec2_keyname: img2caption-keypair
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
